### ISSUE TITLE
Werkt kut omdat svrem het weer eens heeft verneukt

### ISSUE THREAD

**Issue by Zon146** [Prutsor/bijbel-straattaal#6]
^ lees titel

**Comment by Prutsor** [comment]
wel beetje waar

**Comment by svrem** [comment]
ez

**Comment by Prutsor** [comment]
![maxresdefault](https://user-images.githubusercontent.com/57110543/142771099-c406ea96-dcec-4a05-b449-f98f9e08dec5.jpg)

**Comment by svrem** [comment]
- [ ] ja
- [ ] nee
- [x] nee
- [x] nee
- [ ] ja
- [ ] dit
- [ ] cette

**Comment by Prutsor** [comment]
werkrt weer ez

**Comment by Zon146** [comment]
Ziek
